apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: fluxora-gateway
  namespace: fluxora
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fluxora-api
  namespace: fluxora
spec:
  hosts:
    - "*"
  gateways:
    - fluxora-gateway
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: fluxora-api
            port:
              number: 8000
          weight: 100
      retries:
        attempts: 3
        perTryTimeout: 2s
      timeout: 5s
      fault:
        delay:
          percentage:
            value: 0
          fixedDelay: 0s
        abort:
          percentage:
            value: 0
          httpStatus: 500
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: fluxora-api
  namespace: fluxora
spec:
  host: fluxora-api
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 30ms
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutiveErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 100
