apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxora-service-registry
  namespace: fluxora
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
      - name: service-registry
        image: consul:1.14.2
        ports:
        - containerPort: 8500
          name: http
        - containerPort: 8600
          name: dns
          protocol: UDP
        - containerPort: 8600
          name: dns-tcp
          protocol: TCP
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: CONSUL_BIND_INTERFACE
          value: eth0
        - name: CONSUL_CLIENT_INTERFACE
          value: eth0
        args:
        - "agent"
        - "-server"
        - "-bootstrap-expect=3"
        - "-ui"
        - "-client=0.0.0.0"
        livenessProbe:
          httpGet:
            path: /v1/status/leader
            port: 8500
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v1/status/leader
            port: 8500
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: fluxora
spec:
  selector:
    app: service-registry
  ports:
  - name: http
    port: 8500
    targetPort: 8500
  - name: dns
    port: 8600
    targetPort: 8600
    protocol: UDP
  - name: dns-tcp
    port: 8600
    targetPort: 8600
    protocol: TCP
  type: ClusterIP
