stages:
  process_data:
    cmd: python src/data/make_dataset.py
    deps:
      - data/raw
    outs:
      - data/processed
    metrics:
      - reports/data_stats.json

  train_model:
    cmd: python src/models/train.py
    deps:
      - data/processed
      - src/models
    outs:
      - models/production