# Database Infrastructure for Financial Standards Compliance
# This configuration implements secure, highly available database systems

apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
    compliance: "pci-dss,gdpr,soc2"
    data-classification: "restricted"

---
# MySQL Primary-Replica Configuration with Encryption
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-primary
  namespace: database
  labels:
    app: mysql
    role: primary
    compliance: "pci-dss,gdpr,soc2"
spec:
  serviceName: mysql-primary
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      role: primary
  template:
    metadata:
      labels:
        app: mysql
        role: primary
        compliance: "pci-dss,gdpr,soc2"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
        fluxora.com/backup-required: "true"
        fluxora.com/encryption-required: "true"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      
      initContainers:
      - name: mysql-init
        image: mysql:8.0
        command:
        - /bin/bash
        - -c
        - |
          set -e
          
          # Initialize MySQL data directory if empty
          if [ ! -d "/var/lib/mysql/mysql" ]; then
            mysqld --initialize-insecure --user=mysql --datadir=/var/lib/mysql
          fi
          
          # Set proper permissions
          chown -R mysql:mysql /var/lib/mysql
          chmod 750 /var/lib/mysql
        
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        
        securityContext:
          runAsUser: 0  # Need root for initialization
          runAsGroup: 0
          allowPrivilegeEscalation: true
      
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        - containerPort: 33060
          name: mysqlx
        
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-credentials
              key: password
        - name: MYSQL_DATABASE
          value: "fluxora"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-app-credentials
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-app-credentials
              key: password
        - name: MYSQL_REPLICATION_USER
          valueFrom:
            secretKeyRef:
              name: mysql-replication-credentials
              key: username
        - name: MYSQL_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-replication-credentials
              key: password
        
        args:
        - --server-id=1
        - --log-bin=mysql-bin
        - --binlog-format=ROW
        - --gtid-mode=ON
        - --enforce-gtid-consistency=ON
        - --log-slave-updates=ON
        - --binlog-checksum=CRC32
        - --master-verify-checksum=ON
        - --slave-sql-verify-checksum=ON
        
        # Security and Compliance Configuration
        - --ssl-ca=/etc/mysql/certs/ca.pem
        - --ssl-cert=/etc/mysql/certs/server-cert.pem
        - --ssl-key=/etc/mysql/certs/server-key.pem
        - --require-secure-transport=ON
        - --tls-version=TLSv1.2,TLSv1.3
        
        # Encryption at Rest
        - --early-plugin-load=keyring_file.so
        - --keyring-file-data=/var/lib/mysql-keyring/keyring
        - --innodb-encrypt-tables=ON
        - --innodb-encrypt-log=ON
        - --innodb-encryption-threads=4
        
        # Audit Logging for Compliance
        - --plugin-load-add=audit_log.so
        - --audit-log=FORCE_PLUS_PERMANENT
        - --audit-log-format=JSON
        - --audit-log-file=/var/log/mysql/audit.log
        - --audit-log-rotate-on-size=100M
        - --audit-log-rotations=10
        
        # Performance and Security Tuning
        - --innodb-buffer-pool-size=2G
        - --innodb-log-file-size=256M
        - --innodb-flush-log-at-trx-commit=1
        - --sync-binlog=1
        - --max-connections=1000
        - --max-user-connections=950
        - --thread-cache-size=50
        - --table-open-cache=4000
        - --query-cache-size=0
        - --query-cache-type=0
        - --slow-query-log=ON
        - --slow-query-log-file=/var/log/mysql/slow.log
        - --long-query-time=2
        - --log-queries-not-using-indexes=ON
        
        # Security Settings
        - --local-infile=OFF
        - --skip-show-database
        - --skip-symbolic-links
        - --secure-file-priv=/var/lib/mysql-files/
        
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/conf.d
          readOnly: true
        - name: mysql-certs
          mountPath: /etc/mysql/certs
          readOnly: true
        - name: mysql-keyring
          mountPath: /var/lib/mysql-keyring
        - name: mysql-logs
          mountPath: /var/log/mysql
        - name: mysql-files
          mountPath: /var/lib/mysql-files
        
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
          requests:
            cpu: 2000m
            memory: 4Gi
        
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - -u
            - root
            - -p$MYSQL_ROOT_PASSWORD
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          exec:
            command:
            - mysql
            - -h
            - localhost
            - -u
            - root
            - -p$MYSQL_ROOT_PASSWORD
            - -e
            - "SELECT 1"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          runAsGroup: 999
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false  # MySQL needs to write to data directory
          capabilities:
            drop:
            - ALL
            add:
            - SETUID
            - SETGID
      
      # MySQL Exporter for Monitoring
      - name: mysql-exporter
        image: prom/mysqld-exporter:latest
        ports:
        - containerPort: 9104
          name: metrics
        
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-exporter-credentials
              key: dsn
        
        args:
        - --collect.info_schema.processlist
        - --collect.info_schema.innodb_metrics
        - --collect.info_schema.innodb_tablespaces
        - --collect.info_schema.innodb_cmp
        - --collect.info_schema.innodb_cmpmem
        - --collect.info_schema.query_response_time
        - --collect.engine_tokudb_status
        - --collect.engine_innodb_status
        - --collect.global_status
        - --collect.global_variables
        - --collect.slave_status
        - --collect.binlog_size
        - --collect.perf_schema.eventswaits
        - --collect.perf_schema.file_events
        - --collect.perf_schema.indexiowaits
        - --collect.perf_schema.tableiowaits
        - --collect.perf_schema.tablelocks
        
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      
      volumes:
      - name: mysql-config
        configMap:
          name: mysql-config
      - name: mysql-certs
        secret:
          secretName: mysql-tls-certs
          defaultMode: 0400
      - name: mysql-keyring
        emptyDir:
          sizeLimit: 1Gi
      - name: mysql-logs
        emptyDir:
          sizeLimit: 5Gi
      - name: mysql-files
        emptyDir:
          sizeLimit: 1Gi
      
      serviceAccountName: mysql-service-account
      
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
      labels:
        app: mysql
        compliance: "pci-dss,gdpr,soc2"
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "gp3-encrypted"
      resources:
        requests:
          storage: 500Gi

---
# MySQL Replica StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-replica
  namespace: database
  labels:
    app: mysql
    role: replica
    compliance: "pci-dss,gdpr,soc2"
spec:
  serviceName: mysql-replica
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      role: replica
  template:
    metadata:
      labels:
        app: mysql
        role: replica
        compliance: "pci-dss,gdpr,soc2"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      
      initContainers:
      - name: mysql-replica-init
        image: mysql:8.0
        command:
        - /bin/bash
        - -c
        - |
          set -e
          
          # Initialize MySQL data directory if empty
          if [ ! -d "/var/lib/mysql/mysql" ]; then
            mysqld --initialize-insecure --user=mysql --datadir=/var/lib/mysql
          fi
          
          # Set proper permissions
          chown -R mysql:mysql /var/lib/mysql
          chmod 750 /var/lib/mysql
        
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: true
      
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        - containerPort: 33060
          name: mysqlx
        
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-credentials
              key: password
        - name: MYSQL_REPLICATION_USER
          valueFrom:
            secretKeyRef:
              name: mysql-replication-credentials
              key: username
        - name: MYSQL_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-replication-credentials
              key: password
        
        args:
        - --server-id=2  # Will be overridden by init script for multiple replicas
        - --log-bin=mysql-bin
        - --binlog-format=ROW
        - --gtid-mode=ON
        - --enforce-gtid-consistency=ON
        - --log-slave-updates=ON
        - --read-only=ON
        - --super-read-only=ON
        - --relay-log=relay-bin
        - --relay-log-index=relay-bin.index
        
        # Same security and compliance settings as primary
        - --ssl-ca=/etc/mysql/certs/ca.pem
        - --ssl-cert=/etc/mysql/certs/server-cert.pem
        - --ssl-key=/etc/mysql/certs/server-key.pem
        - --require-secure-transport=ON
        - --tls-version=TLSv1.2,TLSv1.3
        
        # Encryption at Rest
        - --early-plugin-load=keyring_file.so
        - --keyring-file-data=/var/lib/mysql-keyring/keyring
        - --innodb-encrypt-tables=ON
        - --innodb-encrypt-log=ON
        - --innodb-encryption-threads=4
        
        # Audit Logging
        - --plugin-load-add=audit_log.so
        - --audit-log=FORCE_PLUS_PERMANENT
        - --audit-log-format=JSON
        - --audit-log-file=/var/log/mysql/audit.log
        
        # Performance Tuning (Read-optimized)
        - --innodb-buffer-pool-size=2G
        - --innodb-log-file-size=256M
        - --max-connections=1000
        - --thread-cache-size=50
        - --table-open-cache=4000
        - --query-cache-size=0
        - --query-cache-type=0
        
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/conf.d
          readOnly: true
        - name: mysql-certs
          mountPath: /etc/mysql/certs
          readOnly: true
        - name: mysql-keyring
          mountPath: /var/lib/mysql-keyring
        - name: mysql-logs
          mountPath: /var/log/mysql
        
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 2Gi
        
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - -u
            - root
            - -p$MYSQL_ROOT_PASSWORD
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          exec:
            command:
            - mysql
            - -h
            - localhost
            - -u
            - root
            - -p$MYSQL_ROOT_PASSWORD
            - -e
            - "SELECT 1"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          runAsGroup: 999
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
            add:
            - SETUID
            - SETGID
      
      # MySQL Exporter for Monitoring
      - name: mysql-exporter
        image: prom/mysqld-exporter:latest
        ports:
        - containerPort: 9104
          name: metrics
        
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-exporter-credentials
              key: dsn
        
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      
      volumes:
      - name: mysql-config
        configMap:
          name: mysql-config
      - name: mysql-certs
        secret:
          secretName: mysql-tls-certs
          defaultMode: 0400
      - name: mysql-keyring
        emptyDir:
          sizeLimit: 1Gi
      - name: mysql-logs
        emptyDir:
          sizeLimit: 5Gi
      
      serviceAccountName: mysql-service-account
      
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
      labels:
        app: mysql
        compliance: "pci-dss,gdpr,soc2"
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "gp3-encrypted"
      resources:
        requests:
          storage: 500Gi

---
# MySQL Services
apiVersion: v1
kind: Service
metadata:
  name: mysql-primary
  namespace: database
  labels:
    app: mysql
    role: primary
    compliance: "pci-dss,gdpr,soc2"
spec:
  selector:
    app: mysql
    role: primary
  ports:
  - port: 3306
    name: mysql
    protocol: TCP
  - port: 33060
    name: mysqlx
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-replica
  namespace: database
  labels:
    app: mysql
    role: replica
    compliance: "pci-dss,gdpr,soc2"
spec:
  selector:
    app: mysql
    role: replica
  ports:
  - port: 3306
    name: mysql
    protocol: TCP
  - port: 33060
    name: mysqlx
    protocol: TCP
  type: ClusterIP

---
# MySQL Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: database
  labels:
    app: mysql
    compliance: "pci-dss,gdpr,soc2"
data:
  my.cnf: |
    [mysqld]
    # Basic Settings
    user = mysql
    pid-file = /var/run/mysqld/mysqld.pid
    socket = /var/run/mysqld/mysqld.sock
    port = 3306
    basedir = /usr
    datadir = /var/lib/mysql
    tmpdir = /tmp
    lc-messages-dir = /usr/share/mysql
    
    # Character Set and Collation
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    init-connect = 'SET NAMES utf8mb4'
    
    # InnoDB Settings
    default-storage-engine = InnoDB
    innodb-file-per-table = 1
    innodb-open-files = 400
    innodb-io-capacity = 400
    innodb-flush-method = O_DIRECT
    innodb-log-files-in-group = 2
    innodb-log-buffer-size = 8M
    innodb-flush-log-at-trx-commit = 1
    innodb-lock-wait-timeout = 120
    innodb-doublewrite = 1
    innodb-checksum-algorithm = crc32
    
    # MyISAM Settings
    key-buffer-size = 32M
    myisam-recover-options = BACKUP,FORCE
    
    # Connection Settings
    max-connections = 1000
    max-connect-errors = 1000000
    max-allowed-packet = 256M
    interactive-timeout = 3600
    wait-timeout = 3600
    connect-timeout = 60
    
    # Query Cache (Disabled for MySQL 8.0)
    query-cache-type = 0
    query-cache-size = 0
    
    # Logging
    log-error = /var/log/mysql/error.log
    slow-query-log = 1
    slow-query-log-file = /var/log/mysql/slow.log
    long-query-time = 2
    log-queries-not-using-indexes = 1
    log-slow-admin-statements = 1
    log-slow-slave-statements = 1
    
    # Binary Logging
    log-bin = /var/lib/mysql/mysql-bin
    binlog-format = ROW
    binlog-row-image = FULL
    sync-binlog = 1
    expire-logs-days = 7
    max-binlog-size = 128M
    
    # GTID
    gtid-mode = ON
    enforce-gtid-consistency = ON
    log-slave-updates = ON
    
    # SSL/TLS Configuration
    ssl-ca = /etc/mysql/certs/ca.pem
    ssl-cert = /etc/mysql/certs/server-cert.pem
    ssl-key = /etc/mysql/certs/server-key.pem
    require-secure-transport = ON
    tls-version = TLSv1.2,TLSv1.3
    
    # Security Settings
    local-infile = 0
    skip-show-database
    skip-symbolic-links
    secure-file-priv = /var/lib/mysql-files/
    
    # Performance Schema
    performance-schema = ON
    performance-schema-instrument = 'stage/%=ON'
    performance-schema-instrument = 'statement/%=ON'
    
    [mysql]
    default-character-set = utf8mb4
    
    [client]
    default-character-set = utf8mb4
    ssl-ca = /etc/mysql/certs/ca.pem
    ssl-cert = /etc/mysql/certs/client-cert.pem
    ssl-key = /etc/mysql/certs/client-key.pem

---
# Service Account for MySQL
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-service-account
  namespace: database
  labels:
    app: mysql
    compliance: "pci-dss,gdpr,soc2"
automountServiceAccountToken: true

---
# RBAC for MySQL Service Account
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-role
  namespace: database
  labels:
    app: mysql
    compliance: "pci-dss,gdpr,soc2"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-rolebinding
  namespace: database
  labels:
    app: mysql
    compliance: "pci-dss,gdpr,soc2"
subjects:
- kind: ServiceAccount
  name: mysql-service-account
  namespace: database
roleRef:
  kind: Role
  name: mysql-role
  apiGroup: rbac.authorization.k8s.io

