apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: fluxora
  labels:
    app: alertmanager
    component: monitoring
    compliance: "pci-dss,gdpr,soc2"
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.fluxora.com:587'
      smtp_from: 'alertmanager@fluxora.com'
      smtp_auth_username: 'alertmanager'
      smtp_auth_password_file: '/etc/alertmanager/secrets/smtp_password'
      smtp_require_tls: true
      slack_api_url_file: '/etc/alertmanager/secrets/slack_webhook'
      pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

    templates:
      - '/etc/alertmanager/templates/*.tmpl'

    # Inhibition rules to reduce noise
    inhibit_rules:
      # Inhibit warning alerts if critical alert is firing
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'instance']
      
      # Inhibit node alerts if cluster is down
      - source_match:
          alertname: 'ClusterDown'
        target_match_re:
          alertname: 'Node.*'
        equal: ['cluster']

    route:
      group_by: ['alertname', 'cluster', 'service', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'default-receiver'
      
      routes:
        # Critical security alerts - immediate response required
        - match_re:
            alertname: '^(SecurityBreach|UnauthorizedAccess|DataExfiltration|MalwareDetected).*'
        receiver: 'security-team-critical'
        group_wait: 0s
        repeat_interval: 15m
        continue: false
        
        # PCI DSS compliance alerts
        - match_re:
            compliance: '.*pci-dss.*'
        receiver: 'compliance-team-pci'
        group_wait: 10s
        repeat_interval: 1h
        continue: true
        
        # GDPR compliance alerts
        - match_re:
            compliance: '.*gdpr.*'
        receiver: 'compliance-team-gdpr'
        group_wait: 10s
        repeat_interval: 1h
        continue: true
        
        # SOC 2 compliance alerts
        - match_re:
            compliance: '.*soc2.*'
        receiver: 'compliance-team-soc2'
        group_wait: 10s
        repeat_interval: 1h
        continue: true
        
        # Critical infrastructure alerts
        - match:
            severity: critical
        receiver: 'infrastructure-critical'
        group_wait: 10s
        repeat_interval: 30m
        continue: true
        
        # Database alerts
        - match_re:
            service: '.*database.*|.*mysql.*|.*redis.*'
        receiver: 'database-team'
        group_wait: 30s
        repeat_interval: 2h
        continue: true
        
        # Application performance alerts
        - match_re:
            alertname: '^(HighLatency|HighErrorRate|LowThroughput).*'
        receiver: 'application-team'
        group_wait: 1m
        repeat_interval: 2h
        continue: true
        
        # Certificate expiration alerts
        - match_re:
            alertname: '^CertificateExpir.*'
        receiver: 'security-team-certs'
        group_wait: 5m
        repeat_interval: 24h
        continue: true
        
        # Backup and recovery alerts
        - match_re:
            alertname: '^(BackupFailed|RestoreFailed).*'
        receiver: 'backup-team'
        group_wait: 2m
        repeat_interval: 6h
        continue: true
        
        # Warning level alerts
        - match:
            severity: warning
        receiver: 'general-warnings'
        group_wait: 2m
        repeat_interval: 6h
        continue: false

    receivers:
      # Default receiver for unmatched alerts
      - name: 'default-receiver'
        slack_configs:
          - channel: '#alerts-general'
            send_resolved: true
            title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
            text: |
              {{ range .Alerts }}
              *Alert:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              *Severity:* {{ .Labels.severity }}
              *Service:* {{ .Labels.service }}
              *Instance:* {{ .Labels.instance }}
              *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
              {{ if .Annotations.runbook_url }}*Runbook:* {{ .Annotations.runbook_url }}{{ end }}
              {{ end }}
            color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
        
      # Critical security incidents
      - name: 'security-team-critical'
        pagerduty_configs:
          - routing_key_file: '/etc/alertmanager/secrets/pagerduty_security_key'
            description: 'CRITICAL SECURITY ALERT: {{ .CommonLabels.alertname }}'
            severity: 'critical'
            details:
              alert_count: '{{ len .Alerts }}'
              environment: '{{ .CommonLabels.environment }}'
              cluster: '{{ .CommonLabels.cluster }}'
        slack_configs:
          - channel: '#security-critical'
            send_resolved: true
            title: '🚨 CRITICAL SECURITY ALERT: {{ .CommonLabels.alertname }}'
            text: |
              {{ range .Alerts }}
              *IMMEDIATE ACTION REQUIRED*
              *Alert:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              *Affected System:* {{ .Labels.instance }}
              *Environment:* {{ .Labels.environment }}
              *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
              {{ if .Annotations.runbook_url }}*Incident Response:* {{ .Annotations.runbook_url }}{{ end }}
              {{ end }}
            color: 'danger'
        email_configs:
          - to: 'security-team@fluxora.com,ciso@fluxora.com'
            from: 'alertmanager@fluxora.com'
            subject: 'CRITICAL SECURITY ALERT: {{ .CommonLabels.alertname }}'
            body: |
              CRITICAL SECURITY INCIDENT DETECTED
              
              {{ range .Alerts }}
              Alert: {{ .Annotations.summary }}
              Description: {{ .Annotations.description }}
              Severity: {{ .Labels.severity }}
              Instance: {{ .Labels.instance }}
              Environment: {{ .Labels.environment }}
              Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
              {{ if .Annotations.runbook_url }}Runbook: {{ .Annotations.runbook_url }}{{ end }}
              {{ end }}
              
              This is an automated alert from the Fluxora monitoring system.
              
      # PCI DSS compliance team
      - name: 'compliance-team-pci'
        slack_configs:
          - channel: '#compliance-pci-dss'
            send_resolved: true
            title: '⚠️ PCI DSS Compliance Alert: {{ .CommonLabels.alertname }}'
            text: |
              {{ range .Alerts }}
              *PCI DSS Compliance Issue Detected*
              *Alert:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              *Requirement:* {{ .Labels.pci_requirement | default "General" }}
              *System:* {{ .Labels.instance }}
              *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
              {{ if .Annotations.remediation }}*Remediation:* {{ .Annotations.remediation }}{{ end }}
              {{ end }}
            color: 'warning'
        email_configs:
          - to: 'compliance-team@fluxora.com'
            from: 'alertmanager@fluxora.com'
            subject: 'PCI DSS Compliance Alert: {{ .CommonLabels.alertname }}'
            
      # GDPR compliance team
      - name: 'compliance-team-gdpr'
        slack_configs:
          - channel: '#compliance-gdpr'
            send_resolved: true
            title: '🔒 GDPR Compliance Alert: {{ .CommonLabels.alertname }}'
            text: |
              {{ range .Alerts }}
              *GDPR Compliance Issue Detected*
              *Alert:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              *Data Category:* {{ .Labels.data_category | default "Personal Data" }}
              *System:* {{ .Labels.instance }}
              *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
              {{ if .Annotations.data_protection_impact }}*Impact:* {{ .Annotations.data_protection_impact }}{{ end }}
              {{ end }}
            color: 'warning'
            
      # SOC 2 compliance team
      - name: 'compliance-team-soc2'
        slack_configs:
          - channel: '#compliance-soc2'
            send_resolved: true
            title: '🛡️ SOC 2 Compliance Alert: {{ .CommonLabels.alertname }}'
            text: |
              {{ range .Alerts }}
              *SOC 2 Trust Service Criteria Issue*
              *Alert:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              *Trust Criteria:* {{ .Labels.trust_criteria | default "Security" }}
              *System:* {{ .Labels.instance }}
              *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
              {{ if .Annotations.control_objective }}*Control:* {{ .Annotations.control_objective }}{{ end }}
              {{ end }}
            color: 'warning'
            
      # Critical infrastructure alerts
      - name: 'infrastructure-critical'
        pagerduty_configs:
          - routing_key_file: '/etc/alertmanager/secrets/pagerduty_infra_key'
            description: 'Critical Infrastructure Alert: {{ .CommonLabels.alertname }}'
            severity: 'critical'
        slack_configs:
          - channel: '#infrastructure-critical'
            send_resolved: true
            title: '🔥 CRITICAL: {{ .CommonLabels.alertname }}'
            text: |
              {{ range .Alerts }}
              *Critical Infrastructure Issue*
              *Alert:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              *Service Impact:* {{ .Labels.impact | default "Unknown" }}
              *System:* {{ .Labels.instance }}
              *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
              {{ if .Annotations.runbook_url }}*Runbook:* {{ .Annotations.runbook_url }}{{ end }}
              {{ end }}
            color: 'danger'
            
      # Database team alerts
      - name: 'database-team'
        slack_configs:
          - channel: '#database-alerts'
            send_resolved: true
            title: '💾 Database Alert: {{ .CommonLabels.alertname }}'
            text: |
              {{ range .Alerts }}
              *Database Issue Detected*
              *Alert:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              *Database:* {{ .Labels.database | default .Labels.service }}
              *Instance:* {{ .Labels.instance }}
              *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
              {{ if .Annotations.query }}*Query:* {{ .Annotations.query }}{{ end }}
              {{ end }}
            color: '{{ if eq .Status "firing" }}warning{{ else }}good{{ end }}'
            
      # Application team alerts
      - name: 'application-team'
        slack_configs:
          - channel: '#application-alerts'
            send_resolved: true
            title: '📱 Application Alert: {{ .CommonLabels.alertname }}'
            text: |
              {{ range .Alerts }}
              *Application Performance Issue*
              *Alert:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              *Service:* {{ .Labels.service }}
              *Instance:* {{ .Labels.instance }}
              *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
              {{ if .Annotations.dashboard_url }}*Dashboard:* {{ .Annotations.dashboard_url }}{{ end }}
              {{ end }}
            color: '{{ if eq .Status "firing" }}warning{{ else }}good{{ end }}'
            
      # Certificate management alerts
      - name: 'security-team-certs'
        slack_configs:
          - channel: '#security-certificates'
            send_resolved: true
            title: '🔐 Certificate Alert: {{ .CommonLabels.alertname }}'
            text: |
              {{ range .Alerts }}
              *Certificate Management Issue*
              *Alert:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              *Certificate:* {{ .Labels.cert_name | default .Labels.instance }}
              *Expiry:* {{ .Labels.expiry_date | default "Unknown" }}
              *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
              {{ end }}
            color: 'warning'
            
      # Backup team alerts
      - name: 'backup-team'
        slack_configs:
          - channel: '#backup-recovery'
            send_resolved: true
            title: '💿 Backup Alert: {{ .CommonLabels.alertname }}'
            text: |
              {{ range .Alerts }}
              *Backup/Recovery Issue*
              *Alert:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              *Backup Job:* {{ .Labels.job_name | default .Labels.service }}
              *Instance:* {{ .Labels.instance }}
              *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
              {{ end }}
            color: 'warning'
            
      # General warnings
      - name: 'general-warnings'
        slack_configs:
          - channel: '#alerts-warnings'
            send_resolved: true
            title: '⚠️ Warning: {{ .CommonLabels.alertname }}'
            text: |
              {{ range .Alerts }}
              *Warning Alert*
              *Alert:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              *Service:* {{ .Labels.service }}
              *Instance:* {{ .Labels.instance }}
              *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
              {{ end }}
            color: 'warning'

