defaults:
  - preprocessing: default
  - model: xgboost
  
model:
  xgboost:
    n_estimators: 500
    learning_rate: 0.05
  lstm:
    units: 128
    dropout: 0.2

data:
  source: s3://energy-data-bucket/raw/
  destination: ./data/processed